"""
AUTOSAR ARXML Exporter Module

This module handles exporting parsed data to various formats (CSV, TXT).
"""

import csv
import os
from tkinter import messagebox


class ARXMLExporter:
    """Handles exporting of parsed ARXML data."""

    def __init__(self, parsed_data):
        self.parsed_data = parsed_data

    def export_signals_csv(self, file_path):
        """Export signals data to CSV."""
        try:
            with open(file_path, 'w', newline='', encoding='utf-8') as csvfile:
                fieldnames = ['name', 'data_type', 'length', 'initial_value', 'description']
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

                writer.writeheader()
                for signal in self.parsed_data['signals']:
                    writer.writerow(signal)

            return True, f"Signals exported to {file_path}"

        except Exception as e:
            return False, f"Export failed: {str(e)}"

    def export_ports_csv(self, file_path):
        """Export ports data to CSV."""
        try:
            with open(file_path, 'w', newline='', encoding='utf-8') as csvfile:
                fieldnames = ['name', 'type', 'interface', 'description']
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

                writer.writeheader()
                for port in self.parsed_data['ports']:
                    writer.writerow(port)

            return True, f"Ports exported to {file_path}"

        except Exception as e:
            return False, f"Export failed: {str(e)}"

    def export_runnables_csv(self, file_path):
        """Export runnables data to CSV."""
        try:
            with open(file_path, 'w', newline='', encoding='utf-8') as csvfile:
                fieldnames = ['name', 'symbol', 'event_ref']
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

                writer.writeheader()
                for runnable in self.parsed_data['runnables']:
                    writer.writerow(runnable)

            return True, f"Runnables exported to {file_path}"

        except Exception as e:
            return False, f"Export failed: {str(e)}"

    def export_components_csv(self, file_path):
        """Export software components data to CSV."""
        try:
            with open(file_path, 'w', newline='', encoding='utf-8') as csvfile:
                fieldnames = ['name', 'type', 'internal_behaviors']
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

                writer.writeheader()
                for component in self.parsed_data['software_components']:
                    writer.writerow(component)

            return True, f"Software Components exported to {file_path}"

        except Exception as e:
            return False, f"Export failed: {str(e)}"

    def export_dashboard_txt(self, file_path, summary_counts):
        """Export dashboard summary to TXT file."""
        try:
            with open(file_path, 'w', encoding='utf-8') as txtfile:
                txtfile.write("AUTOSAR ARXML Viewer - Dashboard Summary\n")
                txtfile.write("=" * 50 + "\n\n")

                txtfile.write(f"Total ECU Count: {summary_counts['ecu_count']}\n")
                txtfile.write(f"Total Signals: {summary_counts['signals_count']}\n")
                txtfile.write(f"Total Ports: {summary_counts['ports_count']}\n")
                txtfile.write(f"Total Runnables: {summary_counts['runnables_count']}\n")
                txtfile.write(f"Total Software Components: {summary_counts['components_count']}\n")
                txtfile.write(f"Total XML Nodes: {summary_counts['xml_nodes_count']}\n\n")

                # Add some basic analysis
                txtfile.write("Basic Analysis:\n")
                txtfile.write("-" * 20 + "\n")

                if summary_counts['signals_count'] > 50:
                    txtfile.write("- Large number of signals detected\n")
                elif summary_counts['signals_count'] == 0:
                    txtfile.write("- No signals found\n")

                if summary_counts['runnables_count'] == 0:
                    txtfile.write("- No runnables found\n")

                if summary_counts['ports_count'] < 5:
                    txtfile.write("- Limited port configuration\n")

                if summary_counts['components_count'] > 0:
                    txtfile.write("- Component structure is present\n")

                txtfile.write("\nGenerated by AUTOSAR ARXML Viewer\n")

            return True, f"Dashboard summary exported to {file_path}"

        except Exception as e:
            return False, f"Export failed: {str(e)}"

    def get_default_filename(self, data_type, extension="csv"):
        """Generate a default filename for export."""
        base_name = f"autosar_{data_type}.{extension}"
        counter = 1
        while os.path.exists(base_name):
            base_name = f"autosar_{data_type}_{counter}.{extension}"
            counter += 1
        return base_name

    def show_export_success(self, message):
        """Show success message for export."""
        messagebox.showinfo("Export Successful", message)

    def show_export_error(self, message):
        """Show error message for export."""
        messagebox.showerror("Export Failed", message)

    def export_validation_report(self, file_path, validation_results, summary_counts, insights_text, file_name):
        """Export validation report to TXT file."""
        try:
            import time
            with open(file_path, 'w', encoding='utf-8') as txtfile:
                txtfile.write("AUTOSAR ARXML Validation Report\n")
                txtfile.write("=" * 40 + "\n\n")
                txtfile.write(f"File: {file_name}\n")
                txtfile.write(f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")

                txtfile.write("VALIDATION RESULTS:\n")
                txtfile.write("-" * 20 + "\n")
                for result in validation_results:
                    status_icon = "✔" if result['type'] == 'ok' else "⚠" if result['type'] == 'warning' else "✗"
                    txtfile.write(f"{status_icon} {result['message']}\n")
                txtfile.write("\n")

                txtfile.write("SUMMARY COUNTS:\n")
                txtfile.write("-" * 15 + "\n")
                txtfile.write(f"Total ECU Count: {summary_counts['ecu_count']}\n")
                txtfile.write(f"Total Signals: {summary_counts['signals_count']}\n")
                txtfile.write(f"Total Ports: {summary_counts['ports_count']}\n")
                txtfile.write(f"Total Runnables: {summary_counts['runnables_count']}\n")
                txtfile.write(f"Total Software Components: {summary_counts['components_count']}\n")
                txtfile.write(f"Total XML Nodes: {summary_counts['xml_nodes_count']}\n\n")

                txtfile.write("AI INSIGHTS:\n")
                txtfile.write("-" * 12 + "\n")
                txtfile.write(insights_text + "\n")

                txtfile.write("\nReport generated by AUTOSAR ARXML Viewer\n")

            return True, f"Validation report exported to {file_path}"

        except Exception as e:
            return False, f"Export failed: {str(e)}"